### PR TITLE
Fix seq_no persisting across sessions

### PR DESCRIPTION
**Pull request by funous**
When using an instance of the client to run multiple sessions (calling
.run multiple times), the seq_no of the subsequent sessions didn't start
with a zero. Now it does, so we send the same messages regardless of
using single or multiple client instances to run multiple sessions.

### CODE REVIEW

**Comment by viren-nadkarni** [comment]
Please bump VERSION and update CHANGELOG

**Review by viren-nadkarni — CHANGES_REQUESTED** [review]
Please bump VERSION and update CHANGELOG

**Comment by funous** [comment]
> Please bump VERSION and update CHANGELOG

Done

**Review by viren-nadkarni — APPROVED** [review]

**Comment by viren-nadkarni** [comment]
@funous could you please update your branch so that the CI is triggered?

**Pull request merged**
